# Server
#destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor/*']
#port:             9001

# Custom vars
current_version:  3.0.0
repo:             https://github.com/ExactTarget/fuelux

download:
  source:         https://github.com/ExactTarget/fuelux/archive/3.0.0.zip
  dist:           https://github.com/ExactTarget/fuelux/releases/download/3.0.0/3.0.0.zip
  sass:           https://www.google.com
  
# To view gh-pages locally
# bundle exec jekyll serve