# Server
#destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", 'config.ru', 'Gemfile', 'Gemfile.lock', 'bundle']
#port:             9001

# Custom vars
current_version:  3.0.0
repo:             https://github.com/ExactTarget/fuelux

download:
  source:         https://github.com/ExactTarget/fuelux/archive/3.0.0.zip
  dist:           https://github.com/ExactTarget/fuelux/raw/master/dist/fuelux.zip

blog:             http://code.exacttarget.com

cdn:
  css:            //www.fuelcdn.com/3.0.0/dist/css/fuelux.min.css
  js:             //www.fuelcdn.com/3.0.0/dist/js/fuelux.min.js
  js_dir:         //www.fuelcdn.com/3.0.0/js/
  zip:            //www.fuelcdn.com/3.0.0/dist/fuelux.zip

bootstrap:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.js

 # To view gh-pages locally
# bundle exec jekyll serve
